sudo: required

services:
  - docker

env:
  - DOCKERFILE=plplot/debian-latest
  - DOCKERFILE=plplot/opensuse-tumbleweed
    
install:
  - docker pull $DOCKERFILE
  
script:
  - docker run $DOCKERFILE

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - hbabcock@mac.com
    on_success: never
    on_failure: always
