sudo: required
dist: trusty
language: generic

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang
      env: CC='clang' CXX='clang++'
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8
            - gfortran-4.8
      env: CC='gcc-4.8' CXX='g++-4.8' FC='gfortran-4.8'
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - gfortran-4.9
      env: CC='gcc-4.9' CXX='g++-4.9' FC='gfortran-4.9'
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - gfortran-5
      env: CC='gcc-5' CXX='g++-5' FC='gfortran-5'
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gfortran-6
      env: CC='gcc-6' CXX='g++-6' FC='gfortran-6'

	    
before_install:
  - sudo apt-get -qq update
#  - sudo apt-get --yes install camlidl
  - sudo apt-get --yes install cmake
#  - sudo apt-get --yes install gfortran
#  - sudo apt-get --yes install gnat
  - sudo apt-get --yes install libqhull-dev
  - sudo apt-get --yes install libxml-dom-perl  
  - sudo apt-get --yes install libxml-parser-perl
  - sudo apt-get --yes install default-jdk
  - sudo apt-get --yes install default-jre
  - sudo apt-get --yes install itcl3
  - sudo apt-get --yes install itcl3-dev
  - sudo apt-get --yes install libcairo-dev
  - sudo apt-get --yes install liboctave-dev
  - sudo apt-get --yes install libpango1.0-dev
  - sudo apt-get --yes install libpangocairo-1.0-0
#  - sudo apt-get --yes install libwxgtk3.0-dev
  - sudo apt-get --yes install liblua50
  - sudo apt-get --yes install liblua50-dev
  - sudo apt-get --yes install lua50
#  - sudo apt-get --yes install ocaml	
  - sudo apt-get --yes install octave
  - sudo apt-get --yes install pdl 
  - sudo apt-get --yes install python-dev
  - sudo apt-get --yes install python-numpy
  - sudo apt-get --yes install swig
  - sudo apt-get --yes install tk8.5-dev
  - sudo apt-get --yes install itk3


#  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get --yes --force-yes update && sudo apt-get --yes --force-yes install libgsl0-dev ; fi
#  - if [ $TRAVIS_OS_NAME == osx ]; then brew uninstall --force gcc carthage && brew update && brew upgrade && brew install ${BREW} ; fi

script:
  - cmake -DBUILD_TEST=ON
  - make
  - ctest

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - hbabcock@mac.com
    on_success: never
    on_failure: always
